<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="87488" started-at="2018-06-22T08:49:31Z" finished-at="2018-06-22T08:50:59Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="87488" started-at="2018-06-22T08:49:31Z" finished-at="2018-06-22T08:50:59Z">
      <class name="TestPackage.SPMTests">
        <test-method status="PASS" signature="setUp()[pri:0, instance:TestPackage.SPMTests@146ba0ac]" name="setUp" is-config="true" duration-ms="46815" started-at="2018-06-22T08:49:31Z" finished-at="2018-06-22T08:50:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyLogo()[pri:0, instance:TestPackage.SPMTests@146ba0ac]" name="verifyLogo" duration-ms="215" started-at="2018-06-22T08:50:18Z" finished-at="2018-06-22T08:50:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogo -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestPackage.SPMTests@146ba0ac]" name="tearDown" is-config="true" duration-ms="802" started-at="2018-06-22T08:50:18Z" finished-at="2018-06-22T08:50:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:TestPackage.SPMTests@146ba0ac]" name="setUp" is-config="true" duration-ms="38875" started-at="2018-06-22T08:50:19Z" finished-at="2018-06-22T08:50:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyUsernameEntry()[pri:0, instance:TestPackage.SPMTests@146ba0ac]" name="verifyUsernameEntry" duration-ms="4" started-at="2018-06-22T08:50:58Z" finished-at="2018-06-22T08:50:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at TestPackage.SPMTests.verifyUsernameEntry(SPMTests.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUsernameEntry -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestPackage.SPMTests@146ba0ac]" name="tearDown" is-config="true" duration-ms="727" started-at="2018-06-22T08:50:58Z" finished-at="2018-06-22T08:50:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestPackage.SPMTests -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
